// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8brrYRTbPrsJXqXmTmnoRW9_0RCuPnhI',
    appId: '1:985941268926:web:6e056b396c95114bcc41ef',
    messagingSenderId: '985941268926',
    projectId: 'elephant-tracker-44677',
    authDomain: 'elephant-tracker-44677.firebaseapp.com',
    databaseURL: 'https://elephant-tracker-44677-default-rtdb.firebaseio.com',
    storageBucket: 'elephant-tracker-44677.firebasestorage.app',
    measurementId: 'G-CRV9B496PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCviFc71eV-7WpGdHWMBUO30Yii2O_emfs',
    appId: '1:985941268926:android:c8cda9c6ebdf8d6acc41ef',
    messagingSenderId: '985941268926',
    projectId: 'elephant-tracker-44677',
    databaseURL: 'https://elephant-tracker-44677-default-rtdb.firebaseio.com',
    storageBucket: 'elephant-tracker-44677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_uiAAW-6C7uZeWQC5krMY3055409z4I',
    appId: '1:985941268926:ios:804469c665fb7598cc41ef',
    messagingSenderId: '985941268926',
    projectId: 'elephant-tracker-44677',
    databaseURL: 'https://elephant-tracker-44677-default-rtdb.firebaseio.com',
    storageBucket: 'elephant-tracker-44677.firebasestorage.app',
    iosBundleId: 'com.example.elephantTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl_uiAAW-6C7uZeWQC5krMY3055409z4I',
    appId: '1:985941268926:ios:804469c665fb7598cc41ef',
    messagingSenderId: '985941268926',
    projectId: 'elephant-tracker-44677',
    databaseURL: 'https://elephant-tracker-44677-default-rtdb.firebaseio.com',
    storageBucket: 'elephant-tracker-44677.firebasestorage.app',
    iosBundleId: 'com.example.elephantTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8brrYRTbPrsJXqXmTmnoRW9_0RCuPnhI',
    appId: '1:985941268926:web:a1145feaf42eb255cc41ef',
    messagingSenderId: '985941268926',
    projectId: 'elephant-tracker-44677',
    authDomain: 'elephant-tracker-44677.firebaseapp.com',
    databaseURL: 'https://elephant-tracker-44677-default-rtdb.firebaseio.com',
    storageBucket: 'elephant-tracker-44677.firebasestorage.app',
    measurementId: 'G-PEKSZGT67L',
  );

  
}